DirectionalLight Class Reference
#include <DirectionalLight.h>
Public Member Functions
DirectionalLight ()
DirectionalLight (GLuint shadow_width, GLuint shadow_height, GLfloat red, GLfloat green, GLfloat blue, GLfloat radiance, GLfloat x_dir, GLfloat y_dir, GLfloat z_dir, GLfloat near_plane, GLfloat far_plane, int num_cascades)
glm::mat4 calculate_light_transform ()
std::shared_ptr< CascadedShadowMap > get_shadow_map () const
glm::vec3 get_direction () const
glm::vec3 get_color () const
float get_radiance () const
glm::mat4 get_light_view_matrix () const
std::vector< GLfloat > get_cascaded_slots () const
std::vector< glm::mat4 > & get_cascaded_light_matrices ()
void set_direction (glm::vec3 direction)
void set_radiance (float radiance)
void set_color (glm::vec3 color)
void update_shadow_map (GLfloat shadow_width, GLfloat shadow_height, GLuint num_cascades)
void calc_orthogonal_projections (glm::mat4 camera_view_matrix, GLfloat fov, GLuint window_width, GLuint window_height, GLuint current_num_cascades)
~DirectionalLight ()
Private Member Functions
std::vector< glm::vec4 > get_frustum_corners_world_space (const glm::mat4 &proj, const glm::mat4 &view)
void calc_cascaded_slots ()
Private Attributes
std::shared_ptr< CascadedShadowMap > shadow_map
glm::vec3 direction
GLfloat shadow_near_plane
GLfloat shadow_far_plane
std::array< GLfloat, NUM_CASCADES+1 > cascade_slots
std::vector< glm::mat4 > cascade_light_matrices
Additional Inherited Members
Detailed Description
Definition at line 10 of file DirectionalLight.h.
Constructor & Destructor Documentation
DirectionalLight() [1/2]
DirectionalLight::DirectionalLight ()
Definition at line 3 of file DirectionalLight.cpp.
    :
      Light(),
      shadow_map(std::make_shared<CascadedShadowMap>()),
      direction(glm::vec3{0, 0, 0}),
      shadow_near_plane(0.f),
      shadow_far_plane(0.f),
      cascade_light_matrices(NUM_CASCADES, glm::mat4(0.f))
{
  light_proj = glm::ortho(-20.0f, 20.0f, -20.0f, 20.0f, 0.1f, 100.f);
}
References Light::light_proj.
DirectionalLight() [2/2]
DirectionalLight::DirectionalLight (GLuint shadow_width, GLuint shadow_height, GLfloat red, GLfloat green, GLfloat blue, GLfloat radiance, GLfloat x_dir, GLfloat y_dir, GLfloat z_dir, GLfloat near_plane, GLfloat far_plane, int num_cascades)
Definition at line 20 of file DirectionalLight.cpp.
    :
      Light(red, green, blue, radiance),
      shadow_map(std::make_shared<CascadedShadowMap>()),
      direction(glm::vec3{x_dir, y_dir, z_dir}),
      shadow_near_plane(near_plane),
      shadow_far_plane(far_plane),
      cascade_light_matrices(NUM_CASCADES, glm::mat4(0.f))
{
  light_proj = glm::ortho(-20.0f, 20.0f, -20.0f, 20.0f, 0.1f, 100.f);
  shadow_map->init(shadow_width, shadow_height, num_cascades);
}
References Light::light_proj, and shadow_map.
 DirectionalLight()
DirectionalLight::~DirectionalLight ()
Definition at line 197 of file DirectionalLight.cpp.
{}
Member Function Documentation
calc_cascaded_slots()
void DirectionalLight::calc_cascaded_slots () [private]
Definition at line 93 of file DirectionalLight.cpp.
                                           {
  GLuint number_of_elements = shadow_map->get_num_active_cascades();
  for (int i = 0; i < NUM_CASCADES + 1; i++) {
    cascade_slots[i] = 100000.f;
  }
  for (int i = 0; i < static_cast<int>(number_of_elements + 1); i++) {
    if (i == 0) {
      (cascade_slots)[i] = shadow_near_plane;
    } else {
      (cascade_slots)[i] =
          (shadow_far_plane) * ((GLfloat)i / (GLfloat)(number_of_elements));
    }
  }
  // cascade_slots = { shadow_near_plane, shadow_far_plane / 50.f,
  // shadow_far_plane / 25.f, shadow_far_plane };
  return;
}
References cascade_slots, NUM_CASCADES, shadow_far_plane, shadow_map, and shadow_near_plane.
Referenced by calc_orthogonal_projections().
calc_orthogonal_projections()
void DirectionalLight::calc_orthogonal_projections (glm::mat4 camera_view_matrix, GLfloat fov, GLuint window_width, GLuint window_height, GLuint current_num_cascades)
Definition at line 116 of file DirectionalLight.cpp.
                                                       {
  // calc the start and end point for our cascaded shadow maps
  calc_cascaded_slots();
  for (int i = 0; i < static_cast<int>(current_num_cascades); i++) {
    glm::mat4 curr_cascade_proj = glm::perspective(
        glm::radians(fov), (float)window_width / (float)window_height,
        cascade_slots[i], cascade_slots[i + 1]);
    std::vector<glm::vec4> frustumCornerWorldSpace =
        get_frustum_corners_world_space(curr_cascade_proj, camera_view_matrix);
    glm::vec3 center = glm::vec3(0, 0, 0);
    for (const auto& v : frustumCornerWorldSpace) {
      center += glm::vec3(v);
    }
    center /= frustumCornerWorldSpace.size();
    glm::mat4 light_view_matrix = glm::lookAt(center - get_direction(), center,
                                              glm::vec3(0.0f, 1.0f, 0.0f));
    // the # of frustum corners = 8
    GLfloat minX = std::numeric_limits<float>::max();
    GLfloat maxX = std::numeric_limits<float>::min();
    GLfloat minY = std::numeric_limits<float>::max();
    GLfloat maxY = std::numeric_limits<float>::min();
    GLfloat minZ = std::numeric_limits<float>::max();
    GLfloat maxZ = std::numeric_limits<float>::min();
    for (unsigned int m = 0; m < frustumCornerWorldSpace.size(); m++) {
      // transform each corner from view to world space
      glm::vec4 v_light_view = light_view_matrix * frustumCornerWorldSpace[m];
      // now go to light space
      minX = std::min(minX, v_light_view.x);
      maxX = std::max(maxX, v_light_view.x);
      // we always have negativ y values
      minY = std::min(minY, v_light_view.y);
      maxY = std::max(maxY, v_light_view.y);
      minZ = std::min(minZ, v_light_view.z);
      maxZ = std::max(maxZ, v_light_view.z);
    }
    // Tune this parameter according to the scene
    // for having objects casting shadows that are actually not in the frustum
    // :)
    constexpr float zMult = 10.0f;
    if (minZ < 0) {
      minZ *= zMult;
    } else {
      minZ /= zMult;
    }
    if (maxZ < 0) {
      maxZ /= zMult;
    } else {
      maxZ *= zMult;
    }
    glm::mat4 light_projection = glm::ortho(minX, maxX, minY, maxY, minZ, maxZ);
    cascade_light_matrices[i] = light_projection * light_view_matrix;
  }
}
References calc_cascaded_slots(), cascade_light_matrices, cascade_slots, get_direction(), and get_frustum_corners_world_space().
calculate_light_transform()
glm::mat4 DirectionalLight::calculate_light_transform ()
Definition at line 183 of file DirectionalLight.cpp.
                                                    {
  return light_proj * get_light_view_matrix();
}
References get_light_view_matrix(), and Light::light_proj.
get_cascaded_light_matrices()
std::vector< glm::mat4 > & DirectionalLight::get_cascaded_light_matrices ()
Definition at line 64 of file DirectionalLight.cpp.
                                                                  {
  return cascade_light_matrices;
}
References cascade_light_matrices.
get_cascaded_slots()
std::vector< GLfloat > DirectionalLight::get_cascaded_slots () const
Definition at line 54 of file DirectionalLight.cpp.
                                                              {
  std::vector<GLfloat> result;
  for (int i = 0; i < NUM_CASCADES + 1; i++) {
    result.push_back(cascade_slots[i]);
  }
  return result;
}
References cascade_slots, and NUM_CASCADES.
get_color()
glm::vec3 DirectionalLight::get_color () const
Definition at line 50 of file DirectionalLight.cpp.
{ return color; }
References Light::color.
get_direction()
glm::vec3 DirectionalLight::get_direction () const
Definition at line 48 of file DirectionalLight.cpp.
{ return direction; }
References direction.
Referenced by calc_orthogonal_projections().
get_frustum_corners_world_space()
std::vector< glm::vec4 > DirectionalLight::get_frustum_corners_world_space (const glm::mat4 & proj, const glm::mat4 & view) [private]
Definition at line 75 of file DirectionalLight.cpp.
                                              {
  const auto inv = glm::inverse(proj * view);
  std::vector<glm::vec4> frustumCorners;
  for (unsigned int x = 0; x < 2; ++x) {
    for (unsigned int y = 0; y < 2; ++y) {
      for (unsigned int z = 0; z < 2; ++z) {
        const glm::vec4 pt = inv * glm::vec4(2.0f * x - 1.0f, 2.0f * y - 1.0f,
                                             2.0f * z - 1.0f, 1.0f);
        frustumCorners.push_back(pt / pt.w);
      }
    }
  }
  return frustumCorners;
}
Referenced by calc_orthogonal_projections().
get_light_view_matrix()
glm::mat4 DirectionalLight::get_light_view_matrix () const
Definition at line 43 of file DirectionalLight.cpp.
                                                      {
  return glm::lookAt(direction, glm::vec3(0.0f, 0.0f, 0.0f),
                     glm::vec3(0.0f, 1.0f, 0.0f));
}
References direction.
Referenced by calculate_light_transform().
get_radiance()
float DirectionalLight::get_radiance () const
Definition at line 52 of file DirectionalLight.cpp.
{ return radiance; }
References Light::radiance.
get_shadow_map()
std::shared_ptr< CascadedShadowMap > DirectionalLight::get_shadow_map () const [inline]
Definition at line 21 of file DirectionalLight.h.
                                                          {
    return shadow_map;
  }
References shadow_map.
set_color()
void DirectionalLight::set_color (glm::vec3 color)
Definition at line 195 of file DirectionalLight.cpp.
{ this->color = color; }
References Light::color.
set_direction()
void DirectionalLight::set_direction (glm::vec3 direction)
Definition at line 187 of file DirectionalLight.cpp.
                                                      {
  this->direction = direction;
}
References direction.
set_radiance()
void DirectionalLight::set_radiance (float radiance)
Definition at line 191 of file DirectionalLight.cpp.
                                                  {
  this->radiance = radiance;
}
References Light::radiance.
update_shadow_map()
void DirectionalLight::update_shadow_map (GLfloat shadow_width, GLfloat shadow_height, GLuint num_cascades)
Definition at line 68 of file DirectionalLight.cpp.
                                                              {
  shadow_map.reset(new CascadedShadowMap);
  shadow_map->init((GLuint)shadow_width, (GLuint)shadow_height, num_cascades);
}
References shadow_map.
Field Documentation
cascade_light_matrices
std::vector<glm::mat4> DirectionalLight::cascade_light_matrices [private]
Definition at line 56 of file DirectionalLight.h.
Referenced by calc_orthogonal_projections(), and get_cascaded_light_matrices().
cascade_slots
std::array<GLfloat, NUM_CASCADES + 1> DirectionalLight::cascade_slots [private]
Definition at line 55 of file DirectionalLight.h.
Referenced by calc_cascaded_slots(), calc_orthogonal_projections(), and get_cascaded_slots().
direction
glm::vec3 DirectionalLight::direction [private]
Definition at line 52 of file DirectionalLight.h.
Referenced by get_direction(), get_light_view_matrix(), and set_direction().
shadow_far_plane
GLfloat DirectionalLight::shadow_far_plane [private]
Definition at line 53 of file DirectionalLight.h.
Referenced by calc_cascaded_slots().
shadow_map
std::shared_ptr<CascadedShadowMap> DirectionalLight::shadow_map [private]
Definition at line 50 of file DirectionalLight.h.
Referenced by calc_cascaded_slots(), DirectionalLight(), get_shadow_map(), and update_shadow_map().
shadow_near_plane
GLfloat DirectionalLight::shadow_near_plane [private]
Definition at line 53 of file DirectionalLight.h.
Referenced by calc_cascaded_slots().
The documentation for this class was generated from the following files:
C:/Users/jonas/Desktop/GraphicEngine/Src/scene/light/directional_light/DirectionalLight.h
C:/Users/jonas/Desktop/GraphicEngine/Src/scene/light/directional_light/DirectionalLight.cpp