File Class Reference
#include <File.h>
Public Member Functions
File (const std::string &file_location)
std::string read ()
~File ()
Private Member Functions
std::string makePathsWithBlanksPossible (const std::string &file_location_with_possible_blanks)
Private Attributes
std::string file_location
Detailed Description
Definition at line 4 of file File.h.
Constructor & Destructor Documentation
File()
File::File (const std::string & file_location) [explicit]
Definition at line 6 of file File.cpp.
                                         {
  this->file_location = file_location;
}
References file_location.
 File()
File::~File ()
Definition at line 30 of file File.cpp.
{}
Member Function Documentation
makePathsWithBlanksPossible()
std::string File::makePathsWithBlanksPossible (const std::string & file_location_with_possible_blanks) [private]
Definition at line 34 of file File.cpp.
                                                         {
    std::string new_file_location = file_location_with_possible_blanks;
         const std::string quotationMark = std::string("\"");
    new_file_location.insert(0, quotationMark);
         new_file_location+=(quotationMark);
  return std::string();
}
Referenced by read().
read()
std::string File::read ()
Definition at line 10 of file File.cpp.
                     {
  std::string content;
  std::string fileLocationWrappedInquotationMarks = makePathsWithBlanksPossible(file_location);
  std::ifstream file_stream(file_location, std::ios::in);
  if (!file_stream.is_open()) {
    printf("Failed to read %s. File does not exist.", file_location.c_str());
    return "";
  }
  std::string line = "";
  while (!file_stream.eof()) {
    std::getline(file_stream, line);
    content.append(line + "\n");
  }
  file_stream.close();
  return content;
}
References file_location, and makePathsWithBlanksPossible().
Referenced by ShaderProgram::create_computer_shader_program_from_file(), ShaderProgram::create_from_files(), and ShaderIncludes::ShaderIncludes().
Field Documentation
file_location
std::string File::file_location [private]
Definition at line 13 of file File.h.
Referenced by File(), and read().
The documentation for this class was generated from the following files:
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/util/File.h
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/util/File.cpp