OmniShadowMapPass Class Reference
#include <OmniShadowMapPass.h>
Public Member Functions
OmniShadowMapPass ()
void execute (std::shared_ptr< PointLight > p_light, std::shared_ptr< Scene > scene)
void set_game_object_uniforms (glm::mat4 model, glm::mat4 normal_model)
void create_shader_program ()
~OmniShadowMapPass ()
Private Attributes
std::shared_ptr< OmniDirShadowShaderProgram > shader_program
Detailed Description
Definition at line 10 of file OmniShadowMapPass.h.
Constructor & Destructor Documentation
OmniShadowMapPass()
OmniShadowMapPass::OmniShadowMapPass ()
Definition at line 5 of file OmniShadowMapPass.cpp.
{ create_shader_program(); }
References create_shader_program().
 OmniShadowMapPass()
OmniShadowMapPass::~OmniShadowMapPass ()
Definition at line 58 of file OmniShadowMapPass.cpp.
{}
Member Function Documentation
create_shader_program()
void OmniShadowMapPass::create_shader_program () [virtual]
Implements RenderPassSceneDependend.
Definition at line 50 of file OmniShadowMapPass.cpp.
                                              {
  shader_program = std::make_shared<OmniDirShadowShaderProgram>(
      OmniDirShadowShaderProgram{});
  shader_program->create_from_files("rasterizer/shadows/omni_shadow_map.vert",
                                    "rasterizer/shadows/omni_shadow_map.geom",
                                    "rasterizer/shadows/omni_shadow_map.frag");
}
References shader_program.
Referenced by OmniShadowMapPass().
execute()
void OmniShadowMapPass::execute (std::shared_ptr< PointLight > p_light, std::shared_ptr< Scene > scene)
Definition at line 7 of file OmniShadowMapPass.cpp.
                                                            {
  shader_program->use_shader_program();
  glViewport(0, 0, p_light->get_omni_shadow_map()->get_shadow_width(),
             p_light->get_omni_shadow_map()->get_shadow_height());
  p_light->get_omni_shadow_map()->write();
  glClear(GL_DEPTH_BUFFER_BIT);
  shader_program->setUniformVec3(p_light->get_position(), "light_pos");
  shader_program->setUniformFloat(p_light->get_far_plane(), "far_plane");
  std::vector<glm::mat4> light_matrices = p_light->calculate_light_transform();
  std::stringstream ss;
  for (uint32_t i = 0; i < 6; i++) {
    ss << "light_matrices[" << i << "]";
    shader_program->setUniformMatrix4fv(light_matrices[i], ss.str());
  }
  shader_program->validate_program();
  std::vector<std::shared_ptr<GameObject>> game_objects =
      scene->get_game_objects();
  for (std::shared_ptr<GameObject> object : game_objects) {
    /* if (object_is_visible(object)) {*/
    set_game_object_uniforms(object->get_world_trafo(),
                             object->get_normal_world_trafo());
    object->render();
    //}
  }
  glBindFramebuffer(GL_FRAMEBUFFER, 0);
}
References set_game_object_uniforms(), and shader_program.
set_game_object_uniforms()
void OmniShadowMapPass::set_game_object_uniforms (glm::mat4 model, glm::mat4 normal_model) [virtual]
Implements RenderPassSceneDependend.
Definition at line 45 of file OmniShadowMapPass.cpp.
                                                                       {
  shader_program->setUniformMatrix4fv(model, "model");
}
References shader_program.
Referenced by execute().
Field Documentation
shader_program
std::shared_ptr<OmniDirShadowShaderProgram> OmniShadowMapPass::shader_program [private]
Definition at line 24 of file OmniShadowMapPass.h.
Referenced by create_shader_program(), execute(), and set_game_object_uniforms().
The documentation for this class was generated from the following files:
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/scene/light/point_light/OmniShadowMapPass.h
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/scene/light/point_light/OmniShadowMapPass.cpp