LoadingScreen Class Reference
#include <LoadingScreen.h>
Public Member Functions
LoadingScreen ()
void init ()
void render ()
~LoadingScreen ()
Private Member Functions
void create_shader_program ()
Private Attributes
Quad loading_screen_quad
Texture loading_screen_tex
Texture logo_tex
std::shared_ptr< ShaderProgram > loading_screen_shader_program
Detailed Description
Definition at line 6 of file LoadingScreen.h.
Constructor & Destructor Documentation
LoadingScreen()
LoadingScreen::LoadingScreen ()
Definition at line 7 of file LoadingScreen.cpp.
{ create_shader_program(); }
References create_shader_program().
 LoadingScreen()
LoadingScreen::~LoadingScreen ()
Definition at line 52 of file LoadingScreen.cpp.
{}
Member Function Documentation
create_shader_program()
void LoadingScreen::create_shader_program () [private]
Definition at line 43 of file LoadingScreen.cpp.
                                          {
  loading_screen_shader_program =
      std::make_shared<ShaderProgram>(ShaderProgram{});
  loading_screen_shader_program->create_from_files(
      "loading_screen/loading_screen.vert",
      "loading_screen/loading_screen.frag");
}
References loading_screen_shader_program.
Referenced by LoadingScreen().
init()
void LoadingScreen::init ()
Definition at line 9 of file LoadingScreen.cpp.
                         {
  std::stringstream texture_base_dir;
  std::filesystem::path cwd = std::filesystem::current_path();
  texture_base_dir << cwd.string();
  texture_base_dir << RELATIVE_RESOURCE_PATH;
  texture_base_dir << "Textures/";
  std::stringstream texture_loading_screen;
  texture_loading_screen << texture_base_dir.str()
                         << "Loading_Screen/ukraine.jpg";
  loading_screen_tex = Texture(texture_loading_screen.str().c_str(),
                               std::make_shared<RepeatMode>());
  loading_screen_tex.load_texture_without_alpha_channel();
  std::stringstream texture_logo;
  texture_logo << texture_base_dir.str() << "Loading_Screen/Engine_logo.png";
  logo_tex =
      Texture(texture_logo.str().c_str(), std::make_shared<RepeatMode>());
  logo_tex.load_texture_with_alpha_channel();
}
References Texture::load_texture_with_alpha_channel(), Texture::load_texture_without_alpha_channel(), loading_screen_tex, logo_tex, and RELATIVE_RESOURCE_PATH.
Referenced by main().
render()
void LoadingScreen::render ()
Definition at line 31 of file LoadingScreen.cpp.
                           {
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  loading_screen_tex.use_texture(0);
  loading_screen_shader_program->use_shader_program();
  loading_screen_quad.render();
  glBindFramebuffer(GL_FRAMEBUFFER, 0);
}
References loading_screen_quad, loading_screen_shader_program, loading_screen_tex, Quad::render(), and Texture::use_texture().
Referenced by main().
Field Documentation
loading_screen_quad
Quad LoadingScreen::loading_screen_quad [private]
Definition at line 17 of file LoadingScreen.h.
Referenced by render().
loading_screen_shader_program
std::shared_ptr<ShaderProgram> LoadingScreen::loading_screen_shader_program [private]
Definition at line 21 of file LoadingScreen.h.
Referenced by create_shader_program(), and render().
loading_screen_tex
Texture LoadingScreen::loading_screen_tex [private]
Definition at line 18 of file LoadingScreen.h.
Referenced by init(), and render().
logo_tex
Texture LoadingScreen::logo_tex [private]
Definition at line 19 of file LoadingScreen.h.
Referenced by init().
The documentation for this class was generated from the following files:
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/renderer/loading_screen/LoadingScreen.h
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/renderer/loading_screen/LoadingScreen.cpp