var annotated_dup =
[
    [ "std", "d8/dcc/namespacestd.html", [
      [ "hash< Vertex >", "d3/d62/structstd_1_1hash_3_01_vertex_01_4.html", "d3/d62/structstd_1_1hash_3_01_vertex_01_4" ]
    ] ],
    [ "AABB", "dc/d47/class_a_a_b_b.html", "dc/d47/class_a_a_b_b" ],
    [ "Camera", "da/dbb/class_camera.html", "da/dbb/class_camera" ],
    [ "CascadedShadowMap", "d9/d8e/class_cascaded_shadow_map.html", "d9/d8e/class_cascaded_shadow_map" ],
    [ "ClampToEdgeMode", "d9/de4/class_clamp_to_edge_mode.html", "d9/de4/class_clamp_to_edge_mode" ],
    [ "Clouds", "d5/d7e/class_clouds.html", "d5/d7e/class_clouds" ],
    [ "ComputeShaderProgram", "d1/d9a/class_compute_shader_program.html", "d1/d9a/class_compute_shader_program" ],
    [ "DebugApp", "dd/d2e/class_debug_app.html", "dd/d2e/class_debug_app" ],
    [ "DirectionalLight", "d0/db5/class_directional_light.html", "d0/db5/class_directional_light" ],
    [ "DirectionalShadowMapPass", "de/d56/class_directional_shadow_map_pass.html", "de/d56/class_directional_shadow_map_pass" ],
    [ "File", "d1/d31/class_file.html", "d1/d31/class_file" ],
    [ "GameObject", "d0/dd1/class_game_object.html", "d0/dd1/class_game_object" ],
    [ "GBuffer", "df/dbd/class_g_buffer.html", "df/dbd/class_g_buffer" ],
    [ "GeometryPass", "df/d74/class_geometry_pass.html", "df/d74/class_geometry_pass" ],
    [ "GeometryPassShaderProgram", "d0/d2d/class_geometry_pass_shader_program.html", "d0/d2d/class_geometry_pass_shader_program" ],
    [ "GUI", "d3/d57/class_g_u_i.html", "d3/d57/class_g_u_i" ],
    [ "Light", "da/d7c/class_light.html", "da/d7c/class_light" ],
    [ "LightingPass", "db/d91/class_lighting_pass.html", "db/d91/class_lighting_pass" ],
    [ "LightingPassShaderProgram", "dd/da0/class_lighting_pass_shader_program.html", "dd/da0/class_lighting_pass_shader_program" ],
    [ "LoadingScreen", "d9/dd7/class_loading_screen.html", "d9/dd7/class_loading_screen" ],
    [ "Mesh", "dc/dbe/class_mesh.html", "dc/dbe/class_mesh" ],
    [ "MirroredRepeatMode", "d3/dbb/class_mirrored_repeat_mode.html", "d3/dbb/class_mirrored_repeat_mode" ],
    [ "Model", "d0/de3/class_model.html", "d0/de3/class_model" ],
    [ "Noise", "db/d37/class_noise.html", "db/d37/class_noise" ],
    [ "ObjLoader", "d5/dd8/class_obj_loader.html", "d5/dd8/class_obj_loader" ],
    [ "ObjMaterial", "d9/d65/class_obj_material.html", "d9/d65/class_obj_material" ],
    [ "OmniDirShadowMap", "d3/d4e/class_omni_dir_shadow_map.html", "d3/d4e/class_omni_dir_shadow_map" ],
    [ "OmniDirShadowShaderProgram", "da/da7/class_omni_dir_shadow_shader_program.html", "da/da7/class_omni_dir_shadow_shader_program" ],
    [ "OmniShadowMapPass", "d0/d1d/class_omni_shadow_map_pass.html", "d0/d1d/class_omni_shadow_map_pass" ],
    [ "PointLight", "dd/d0a/class_point_light.html", "dd/d0a/class_point_light" ],
    [ "Quad", "d3/df8/class_quad.html", "d3/df8/class_quad" ],
    [ "RandomNumbers", "db/dd5/class_random_numbers.html", "db/dd5/class_random_numbers" ],
    [ "Renderer", "d4/d44/class_renderer.html", "d4/d44/class_renderer" ],
    [ "RenderPass", "d8/d96/class_render_pass.html", "d8/d96/class_render_pass" ],
    [ "RenderPassSceneDependend", "d0/d58/class_render_pass_scene_dependend.html", "d0/d58/class_render_pass_scene_dependend" ],
    [ "RepeatMode", "d3/d30/class_repeat_mode.html", "d3/d30/class_repeat_mode" ],
    [ "Rotation", "df/def/struct_rotation.html", "df/def/struct_rotation" ],
    [ "Scene", "d6/db5/class_scene.html", "d6/db5/class_scene" ],
    [ "ShaderIncludes", "de/d00/class_shader_includes.html", "de/d00/class_shader_includes" ],
    [ "ShaderProgram", "d8/dc4/class_shader_program.html", "d8/dc4/class_shader_program" ],
    [ "ShadowMap", "d8/da9/class_shadow_map.html", "d8/da9/class_shadow_map" ],
    [ "SkyBox", "de/dda/class_sky_box.html", "de/dda/class_sky_box" ],
    [ "Texture", "d2/d7f/class_texture.html", "d2/d7f/class_texture" ],
    [ "TextureWrappingMode", "d5/dba/class_texture_wrapping_mode.html", "d5/dba/class_texture_wrapping_mode" ],
    [ "Vertex", "d7/d62/struct_vertex.html", "d7/d62/struct_vertex" ],
    [ "ViewFrustumCulling", "d9/dd9/class_view_frustum_culling.html", "d9/dd9/class_view_frustum_culling" ],
    [ "Window", "d9/dbf/class_window.html", "d9/dbf/class_window" ]
];