ShaderProgram Class Reference
#include <ShaderProgram.h>
Public Member Functions
ShaderProgram ()
ShaderProgram (const ShaderProgram &)=default
void create_from_files (const char *vertex_location, const char *fragment_location)
void create_from_files (const char *vertex_location, const char *geometry_location, const char *fragment_location)
void create_computer_shader_program_from_file (const char *compute_location)
bool setUniformVec3 (glm::vec3 uniform, const std::string &shaderUniformName)
bool setUniformFloat (GLfloat uniform, const std::string &shaderUniformName)
bool setUniformInt (GLint uniform, const std::string &shaderUniformName)
bool setUniformMatrix4fv (glm::mat4 matrix, const std::string &shaderUniformName)
bool setUniformBlockBinding (GLuint block_binding, const std::string &shaderUniformName)
GLuint get_id () const
void use_shader_program ()
void validate_program ()
~ShaderProgram ()
Protected Member Functions
void add_shader (GLuint program, const char *shader_code, GLenum shader_type)
void compile_shader_program (const char *vertex_code, const char *fragment_code)
void compile_shader_program (const char *vertex_code, const char *geometry_code, const char *fragment_code)
void compile_compute_shader_program (const char *compute_code)
void compile_program ()
bool validateUniformLocation (GLint uniformLocation)
GLuint getUniformLocation (const std::string &shaderUniformName, bool &validity)
void clear_shader_program ()
Protected Attributes
std::string shader_base_dir
GLuint program_id
const char * vertex_location
const char * fragment_location
const char * geometry_location
const char * compute_location
Detailed Description
Definition at line 13 of file ShaderProgram.h.
Constructor & Destructor Documentation
ShaderProgram() [1/2]
ShaderProgram::ShaderProgram ()
Definition at line 9 of file ShaderProgram.cpp.
    :
      program_id(0),
      vertex_location(""),
      fragment_location(""),
      geometry_location(""),
      compute_location("fragment_location")
{
  std::stringstream aux;
  std::filesystem::path cwd = std::filesystem::current_path();
  aux << cwd.string();
  aux << RELATIVE_RESOURCE_PATH;
  aux << "Shaders/";
  shader_base_dir = aux.str();
}
References RELATIVE_RESOURCE_PATH, and shader_base_dir.
ShaderProgram() [2/2]
ShaderProgram::ShaderProgram (const ShaderProgram &) [default]
 ShaderProgram()
ShaderProgram::~ShaderProgram ()
Definition at line 321 of file ShaderProgram.cpp.
{ clear_shader_program(); }
References clear_shader_program().
Member Function Documentation
add_shader()
void ShaderProgram::add_shader (GLuint program, const char * shader_code, GLenum shader_type) [protected]
Definition at line 113 of file ShaderProgram.cpp.
                                                   {
  GLuint shader = glCreateShader(shader_type);
  // the opengl function wants c -style char array of code and the length in an
  // array ... so we do it
  const GLchar* code[1];
  code[0] = shader_code;
  GLint code_length[1];
  code_length[0] = (GLint)strlen(shader_code);
  glShaderSource(shader, 1, code, code_length);
  glCompileShader(shader);
  // glCompileShaderIncludeARB(shader);
  GLint result = 0;
  GLchar eLog[1024] = {0};
  // retrieve status of the shader and print if any error occured
  glGetShaderiv(shader, GL_COMPILE_STATUS, &result);
  if (!result) {
    glGetShaderInfoLog(shader, sizeof(eLog), NULL, eLog);
    printf("Error compiling the %d shader: '%s'\n", shader_type, eLog);
    printf("%s", shader_code);
    return;
  }
  // we are happy, everything went well so attach shader to program
  glAttachShader(program, shader);
}
Referenced by compile_compute_shader_program(), and compile_shader_program().
clear_shader_program()
void ShaderProgram::clear_shader_program () [protected]
Definition at line 312 of file ShaderProgram.cpp.
                                         {
  // don't trash the id's!!
  // delete it from memory!!
  if (program_id != 0) {
    glDeleteProgram(program_id);
    program_id = 0;
  }
}
References program_id.
Referenced by ~ShaderProgram().
compile_compute_shader_program()
void ShaderProgram::compile_compute_shader_program (const char * compute_code) [protected]
Definition at line 182 of file ShaderProgram.cpp.
                                                                           {
  program_id = glCreateProgram();
  if (!program_id) {
    printf("Error creating shader program!\n");
    return;
  }
  add_shader(program_id, compute_code, GL_COMPUTE_SHADER);
  compile_program();
}
References add_shader(), compile_program(), and program_id.
Referenced by create_computer_shader_program_from_file().
compile_program()
void ShaderProgram::compile_program () [protected]
Definition at line 195 of file ShaderProgram.cpp.
                                    {
  // as simple as that; opengl will link it for us :)
  glLinkProgram(program_id);
  GLint result = 0;
  GLchar eLog[1024] = {0};
  glGetProgramiv(program_id, GL_LINK_STATUS, &result);
  if (!result) {
    glGetProgramInfoLog(program_id, sizeof(eLog), NULL, eLog);
    printf("Error linking program: '%s'\n", eLog);
    return;
  }
  validate_program();
}
References program_id, and validate_program().
Referenced by compile_compute_shader_program(), and compile_shader_program().
compile_shader_program() [1/2]
void ShaderProgram::compile_shader_program (const char * vertex_code, const char * fragment_code) [protected]
Definition at line 146 of file ShaderProgram.cpp.
                                                                      {
  // retrieve the id; we need to reference it later on
  program_id = glCreateProgram();
  if (!program_id) {
    printf("Error creating shader program !\n");
    return;
  }
  // we will always need one vertex ShaderProgram
  add_shader(program_id, vertex_code, GL_VERTEX_SHADER);
  // and one fragment ShaderProgram
  add_shader(program_id, fragment_code, GL_FRAGMENT_SHADER);
  // we attached all shaders
  // so compile program
  compile_program();
}
References add_shader(), compile_program(), and program_id.
Referenced by create_from_files().
compile_shader_program() [2/2]
void ShaderProgram::compile_shader_program (const char * vertex_code, const char * geometry_code, const char * fragment_code) [protected]
Definition at line 165 of file ShaderProgram.cpp.
                                                                      {
  program_id = glCreateProgram();
  if (!program_id) {
    printf("Error creating shader program!\n");
    return;
  }
  add_shader(program_id, vertex_code, GL_VERTEX_SHADER);
  add_shader(program_id, geometry_code, GL_GEOMETRY_SHADER);
  add_shader(program_id, fragment_code, GL_FRAGMENT_SHADER);
  compile_program();
}
References add_shader(), compile_program(), and program_id.
create_computer_shader_program_from_file()
void ShaderProgram::create_computer_shader_program_from_file (const char * compute_location)
Definition at line 80 of file ShaderProgram.cpp.
                                  {
  std::stringstream comp_shader;
  comp_shader << shader_base_dir << compute_location;
  File compute_shader_file(comp_shader.str());
  std::string file = compute_shader_file.read();
  const char* compute_code = file.c_str();
  this->compute_location = compute_location;
  compile_compute_shader_program(compute_code);
}
References compile_compute_shader_program(), compute_location, File::read(), and shader_base_dir.
Referenced by ComputeShaderProgram::reload().
create_from_files() [1/2]
void ShaderProgram::create_from_files (const char * vertex_location, const char * fragment_location)
Definition at line 28 of file ShaderProgram.cpp.
                                                                     {
  std::stringstream vertex_shader;
  std::stringstream fragment_shader;
  vertex_shader << shader_base_dir << vertex_location;
  fragment_shader << shader_base_dir << fragment_location;
  File vertex_shader_file(vertex_shader.str());
  File fragment_shader_file(fragment_shader.str());
  std::string vertex_string = vertex_shader_file.read();
  std::string fragment_string = fragment_shader_file.read();
  // we need c-like strings ....
  const char* vertex_code = vertex_string.c_str();
  const char* fragment_code = fragment_string.c_str();
  this->vertex_location = (vertex_location);
  this->fragment_location = (fragment_location);
  compile_shader_program(vertex_code, fragment_code);
}
References compile_shader_program(), fragment_location, File::read(), shader_base_dir, and vertex_location.
Referenced by OmniDirShadowShaderProgram::reload().
create_from_files() [2/2]
void ShaderProgram::create_from_files (const char * vertex_location, const char * geometry_location, const char * fragment_location)
Definition at line 51 of file ShaderProgram.cpp.
                                                                     {
  std::stringstream vertex_shader;
  std::stringstream geometry_shader;
  std::stringstream fragment_shader;
  vertex_shader << shader_base_dir << vertex_location;
  geometry_shader << shader_base_dir << geometry_location;
  fragment_shader << shader_base_dir << fragment_location;
  File vertex_shader_file(vertex_shader.str());
  File geometry_shader_file(geometry_shader.str());
  File fragment_shader_file(fragment_shader.str());
  std::string vertex_string = vertex_shader_file.read();
  std::string geometry_string = geometry_shader_file.read();
  std::string fragment_string = fragment_shader_file.read();
  const char* vertex_code = vertex_string.c_str();
  const char* geometry_code = geometry_string.c_str();
  const char* fragment_code = fragment_string.c_str();
  this->vertex_location = vertex_location;
  this->fragment_location = fragment_location;
  this->geometry_location = geometry_location;
  compile_shader_program(vertex_code, geometry_code, fragment_code);
}
References compile_shader_program(), fragment_location, geometry_location, File::read(), shader_base_dir, and vertex_location.
get_id()
GLuint ShaderProgram::get_id () const
Definition at line 94 of file ShaderProgram.cpp.
{ return program_id; }
References program_id.
getUniformLocation()
GLuint ShaderProgram::getUniformLocation (const std::string & shaderUniformName, bool & validity) [protected]
Definition at line 288 of file ShaderProgram.cpp.
                                                         {
  GLuint uniform_location =
      glGetUniformLocation(program_id, shaderUniformName.c_str());
  validity = validateUniformLocation(uniform_location);
#ifdef NDEBUG
  // nondebug
#else
  if (!validity) {
    /*std::stringstream ss;
            ss << "You have set a wrong uniform! "
                << "Name: " << shaderUniformName << "\n";
            std::cout << ss.str();*/
  }
#endif
  return uniform_location;
}
References program_id, and validateUniformLocation().
Referenced by setUniformFloat(), setUniformInt(), setUniformMatrix4fv(), and setUniformVec3().
setUniformBlockBinding()
bool ShaderProgram::setUniformBlockBinding (GLuint block_binding, const std::string & shaderUniformName)
Definition at line 260 of file ShaderProgram.cpp.
                                                              {
  bool validity = true;
  GLint uniform_location =
      glGetUniformBlockIndex(program_id, shaderUniformName.c_str());
  (uniform_location < 0) ? validity = false : validity = true;
  if (validity) {
    glUniformBlockBinding(program_id, uniform_location, block_binding);
  } else {
#ifdef NDEBUG
    // nondebug
#else
    // printf("Error at setting uniform block binding!");
#endif
  }
  return validity;
}
References program_id.
setUniformFloat()
bool ShaderProgram::setUniformFloat (GLfloat uniform, const std::string & shaderUniformName)
Definition at line 224 of file ShaderProgram.cpp.
                                                                        {
  bool validity = true;
  GLuint uniform_location = getUniformLocation(shaderUniformName, validity);
  if (validity) {
    glUniform1f(uniform_location, uniform);
  }
  return validity;
}
References getUniformLocation().
setUniformInt()
bool ShaderProgram::setUniformInt (GLint uniform, const std::string & shaderUniformName)
Definition at line 236 of file ShaderProgram.cpp.
                                                                      {
  bool validity = true;
  GLuint uniform_location = getUniformLocation(shaderUniformName, validity);
  if (validity) {
    glUniform1i(uniform_location, uniform);
  }
  return validity;
}
References getUniformLocation().
setUniformMatrix4fv()
bool ShaderProgram::setUniformMatrix4fv (glm::mat4 matrix, const std::string & shaderUniformName)
Definition at line 248 of file ShaderProgram.cpp.
                                                                            {
  bool validity = true;
  GLuint uniform_location = getUniformLocation(shaderUniformName, validity);
  if (validity) {
    glUniformMatrix4fv(uniform_location, 1, GL_FALSE, glm::value_ptr(matrix));
  }
  return validity;
}
References getUniformLocation().
setUniformVec3()
bool ShaderProgram::setUniformVec3 (glm::vec3 uniform, const std::string & shaderUniformName)
Definition at line 212 of file ShaderProgram.cpp.
                                                                       {
  bool validity = true;
  GLuint uniform_location = getUniformLocation(shaderUniformName, validity);
  if (validity) {
    glUniform3f(uniform_location, uniform.x, uniform.y, uniform.z);
  }
  return validity;
}
References getUniformLocation().
use_shader_program()
void ShaderProgram::use_shader_program ()
Definition at line 111 of file ShaderProgram.cpp.
{ glUseProgram(program_id); }
References program_id.
validate_program()
void ShaderProgram::validate_program ()
Definition at line 96 of file ShaderProgram.cpp.
                                     {
  GLint result = 0;
  GLchar eLog[1024] = {0};
  glValidateProgram(program_id);
  glGetProgramiv(program_id, GL_VALIDATE_STATUS, &result);
  if (!result) {
    glGetProgramInfoLog(program_id, sizeof(eLog), NULL, eLog);
    printf("Error validating program: '%s'\n", eLog);
    return;
  }
}
References program_id.
Referenced by compile_program().
validateUniformLocation()
bool ShaderProgram::validateUniformLocation (GLint uniformLocation) [protected]
Definition at line 282 of file ShaderProgram.cpp.
                                                                 {
  // if uniform location is invalid (f.e. var disappears because of optimizing
  // of unused vars)
  return (uniformLocation == -1) ? false : true;
}
Referenced by getUniformLocation().
Field Documentation
compute_location
const char* ShaderProgram::compute_location [protected]
Definition at line 51 of file ShaderProgram.h.
Referenced by create_computer_shader_program_from_file(), and ComputeShaderProgram::reload().
fragment_location
const char* ShaderProgram::fragment_location [protected]
Definition at line 49 of file ShaderProgram.h.
Referenced by create_from_files(), and OmniDirShadowShaderProgram::reload().
geometry_location
const char* ShaderProgram::geometry_location [protected]
Definition at line 50 of file ShaderProgram.h.
Referenced by create_from_files(), and OmniDirShadowShaderProgram::reload().
program_id
GLuint ShaderProgram::program_id [protected]
Definition at line 45 of file ShaderProgram.h.
Referenced by clear_shader_program(), compile_compute_shader_program(), compile_program(), compile_shader_program(), get_id(), GeometryPassShaderProgram::get_program_id(), getUniformLocation(), setUniformBlockBinding(), use_shader_program(), and validate_program().
shader_base_dir
std::string ShaderProgram::shader_base_dir [protected]
Definition at line 44 of file ShaderProgram.h.
Referenced by create_computer_shader_program_from_file(), create_from_files(), and ShaderProgram().
vertex_location
const char* ShaderProgram::vertex_location [protected]
Definition at line 48 of file ShaderProgram.h.
Referenced by create_from_files(), and OmniDirShadowShaderProgram::reload().
The documentation for this class was generated from the following files:
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/renderer/ShaderProgram.h
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/renderer/ShaderProgram.cpp