Noise Class Reference
#include <Noise.h>
Public Member Functions
Noise ()
void create_res128_noise ()
void create_res32_noise ()
void read_res128_noise ()
void read_res32_noise ()
void update ()
void set_num_cells (GLuint num_cells_per_axis, GLuint index)
~Noise ()
Private Member Functions
void create_shader_programs ()
void generate_cells (GLuint num_cells_per_axis, GLuint cell_index)
void generate_textures ()
void generate_num_cells_textures ()
void generate_res128_noise_texture ()
void generate_res32_noise_texture ()
void delete_textures ()
void print_comp_shader_capabilities ()
Private Attributes
GLuint texture_1_id
GLuint texture_dim_1
std::shared_ptr< ComputeShaderProgram > texture_1_shader_program
GLuint texture_2_id
GLuint texture_dim_2
std::shared_ptr< ComputeShaderProgram > texture_2_shader_program
GLuint cell_ids [NUM_CELL_POSITIONS]
GLuint num_cells_per_axis [NUM_CELL_POSITIONS]
std::array< std::vector< GLfloat >, NUM_CELL_POSITIONS > cell_data
Detailed Description
Definition at line 17 of file Noise.h.
Constructor & Destructor Documentation
Noise()
Noise::Noise ()
Definition at line 5 of file Noise.cpp.
    :
      texture_dim_1(128),
      texture_dim_2(32)
{
  create_shader_programs();
  // we need 3d-voxel grids with different sizes for
  // creating different worley frequencies
  for (int i = 0; i < NUM_CELL_POSITIONS; i++) {
    num_cells_per_axis[i] = static_cast<GLuint>(pow(2, i + 1));
    generate_cells(num_cells_per_axis[i], i);
  }
  generate_textures();
}
References create_shader_programs(), generate_cells(), generate_textures(), NUM_CELL_POSITIONS, and num_cells_per_axis.
 Noise()
Noise::~Noise ()
Definition at line 284 of file Noise.cpp.
{ delete_textures(); }
References delete_textures().
Member Function Documentation
create_res128_noise()
void Noise::create_res128_noise ()
Definition at line 200 of file Noise.cpp.
                                {
  texture_1_shader_program->use_shader_program();
  texture_1_shader_program->setUniformInt(NOISE_128D_IMAGE_SLOT, "noise");
  std::stringstream ss;
  for (uint32_t i = 0; i < NUM_CELL_POSITIONS; i++) {
    ss << "cell_positions[" << i << "]";
    texture_1_shader_program->setUniformInt(NOISE_CELL_POSITIONS_SLOT + i,
                                            ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "num_cells[" << i << "]";
    texture_1_shader_program->setUniformInt(num_cells_per_axis[i], ss.str());
    ss.clear();
    ss.str(std::string());
    glActiveTexture(GL_TEXTURE0 + NOISE_CELL_POSITIONS_SLOT + i);
    glBindTexture(GL_TEXTURE_3D, cell_ids[i]);
  }
  glDispatchCompute((GLuint)texture_dim_1, (GLuint)texture_dim_1,
                    (GLuint)texture_dim_1);
  // make sure writing to image has finished before read
  glMemoryBarrier(GL_SHADER_IMAGE_ACCESS_BARRIER_BIT);
  // glMemoryBarrier(GL_ALL_BARRIER_BITS);
  glBindTexture(GL_TEXTURE_3D, 0);
}
References cell_ids, NOISE_128D_IMAGE_SLOT, NOISE_CELL_POSITIONS_SLOT, NUM_CELL_POSITIONS, num_cells_per_axis, texture_1_shader_program, and texture_dim_1.
Referenced by update().
create_res32_noise()
void Noise::create_res32_noise ()
Definition at line 233 of file Noise.cpp.
                               {
  texture_2_shader_program->use_shader_program();
  texture_2_shader_program->setUniformInt(NOISE_32D_IMAGE_SLOT, "noise");
  std::stringstream ss;
  for (uint32_t i = 0; i < NUM_CELL_POSITIONS; i++) {
    ss << "cell_positions[" << i << "]";
    texture_2_shader_program->setUniformInt(NOISE_CELL_POSITIONS_SLOT + i,
                                            ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "num_cells[" << i << "]";
    texture_2_shader_program->setUniformInt(num_cells_per_axis[i], ss.str());
    ss.clear();
    ss.str(std::string());
    glActiveTexture(GL_TEXTURE0 + NOISE_CELL_POSITIONS_SLOT + i);
    glBindTexture(GL_TEXTURE_3D, cell_ids[i]);
  }
  glDispatchCompute((GLuint)texture_dim_2, (GLuint)texture_dim_2,
                    (GLuint)texture_dim_2);
  // make sure writing to image has finished before read
  glMemoryBarrier(GL_SHADER_IMAGE_ACCESS_BARRIER_BIT);
  // glMemoryBarrier(GL_ALL_BARRIER_BITS);
  glBindTexture(GL_TEXTURE_3D, 0);
}
References cell_ids, NOISE_32D_IMAGE_SLOT, NOISE_CELL_POSITIONS_SLOT, NUM_CELL_POSITIONS, num_cells_per_axis, texture_2_shader_program, and texture_dim_2.
Referenced by update().
create_shader_programs()
void Noise::create_shader_programs () [private]
Definition at line 24 of file Noise.cpp.
                                   {
  texture_1_shader_program = std::make_shared<ComputeShaderProgram>();
  texture_2_shader_program = std::make_shared<ComputeShaderProgram>();
  texture_1_shader_program->create_computer_shader_program_from_file(
      "clouds/noise_texture_128_res.comp");
  texture_2_shader_program->create_computer_shader_program_from_file(
      "clouds/noise_texture_32_res.comp");
}
References texture_1_shader_program, and texture_2_shader_program.
Referenced by Noise().
delete_textures()
void Noise::delete_textures () [private]
Definition at line 277 of file Noise.cpp.
                            {
  glDeleteTextures(1, &texture_1_id);
  glDeleteTextures(1, &texture_2_id);
  glDeleteTextures(NUM_CELL_POSITIONS, cell_ids);
}
References cell_ids, NUM_CELL_POSITIONS, texture_1_id, and texture_2_id.
Referenced by update(), and ~Noise().
generate_cells()
void Noise::generate_cells (GLuint num_cells_per_axis, GLuint cell_index) [private]
 @ num_cells_per_axis:      current voxel grid dimension
 @ cell_index:                      index into global array for all voxel
 grids
 needed for generating different worley frequencies later on
Definition at line 150 of file Noise.cpp.
                                                                       {
  cell_data[cell_index].reserve(num_cells_per_axis * num_cells_per_axis *
                                num_cells_per_axis * 4);
  // guess which birthday this is ;)
  std::mt19937_64 gen64(25121995);
  std::uniform_real_distribution<float> dis(0, 1);
  // depth
  for (int i = 0; i < static_cast<int>(num_cells_per_axis); i++) {
    // height
    for (int k = 0; k < static_cast<int>(num_cells_per_axis); k++) {
      // width
      for (int m = 0; m < static_cast<int>(num_cells_per_axis); m++) {
        // from:
        // https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage3D.xhtml
        // "The first element corresponds to the lower left corner of the
        // texture image. Subsequent elements progress left-to-right through the
        // remaining texels in the lowest row of the texture image, and then in
        // successively higher rows of the texture image. The final element
        // corresponds to the upper right corner of the texture image."
        const GLfloat random_offset[3] = {dis(gen64), dis(gen64), dis(gen64)};
        GLfloat position[3] = {(m + random_offset[0]), (k + random_offset[1]),
                               (i + random_offset[2])};
        cell_data[cell_index].push_back(position[0]);
        cell_data[cell_index].push_back(position[1]);
        cell_data[cell_index].push_back(position[2]);
        cell_data[cell_index].push_back(1.0f);
        // i leave this more c-style approach for my further me
        // to clearify things :)
        // GLuint index = (i + num_cells_per_axis * (k + m *
        // num_cells_per_axis)) * 4;
        /*GLfloat position[3] = { (i + random_offset[0]),
                                                                                (k + random_offset[1]),
                                                                                (m + random_offset[2])};*/
        /*cell_data[cell_index][index] = position[0];
                                cell_data[cell_index][index + 1] =
           position[1]; cell_data[cell_index][index + 2] = position[2];
                                cell_data[cell_index][index + 3]
           = 1.0f;*/
      }
    }
  }
}
References cell_data, and num_cells_per_axis.
Referenced by Noise(), and update().
generate_num_cells_textures()
void Noise::generate_num_cells_textures () [private]
Definition at line 40 of file Noise.cpp.
                                        {
  glGenTextures(NUM_CELL_POSITIONS, cell_ids);
  for (int i = 0; i < NUM_CELL_POSITIONS; i++) {
    glBindTexture(GL_TEXTURE_3D, cell_ids[i]);
    glTexImage3D(GL_TEXTURE_3D, 0, GL_RGBA32F, num_cells_per_axis[i],
                 num_cells_per_axis[i], num_cells_per_axis[i], 0, GL_RGBA,
                 GL_FLOAT, cell_data[i].data());
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glBindTexture(GL_TEXTURE_3D, 0);
  }
}
References cell_data, cell_ids, NUM_CELL_POSITIONS, and num_cells_per_axis.
Referenced by generate_textures().
generate_res128_noise_texture()
void Noise::generate_res128_noise_texture () [private]
Definition at line 60 of file Noise.cpp.
                                          {
  glGenTextures(1, &texture_1_id);
  glActiveTexture(GL_TEXTURE0 + NOISE_128D_TEXTURES_SLOT);
  glBindTexture(GL_TEXTURE_3D, texture_1_id);
  glTexImage3D(GL_TEXTURE_3D, 0, GL_RGBA32F, texture_dim_1, texture_dim_1,
               texture_dim_1, 0, GL_RGBA, GL_FLOAT, NULL);
  glBindImageTexture(NOISE_128D_IMAGE_SLOT, texture_1_id, 0, GL_FALSE, 0,
                     GL_READ_WRITE, GL_RGBA32F);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glBindTexture(GL_TEXTURE_3D, 0);
}
References NOISE_128D_IMAGE_SLOT, NOISE_128D_TEXTURES_SLOT, texture_1_id, and texture_dim_1.
Referenced by generate_textures().
generate_res32_noise_texture()
void Noise::generate_res32_noise_texture () [private]
Definition at line 81 of file Noise.cpp.
                                         {
  glGenTextures(1, &texture_2_id);
  glActiveTexture(GL_TEXTURE0 + NOISE_32D_TEXTURES_SLOT);
  glBindTexture(GL_TEXTURE_3D, texture_2_id);
  glTexImage3D(GL_TEXTURE_3D, 0, GL_RGBA32F, texture_dim_2, texture_dim_2,
               texture_dim_2, 0, GL_RGBA, GL_FLOAT, NULL);
  glBindImageTexture(NOISE_32D_IMAGE_SLOT, texture_2_id, 0, GL_FALSE, 0,
                     GL_READ_WRITE, GL_RGBA32F);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glBindTexture(GL_TEXTURE_3D, 0);
}
References NOISE_32D_IMAGE_SLOT, NOISE_32D_TEXTURES_SLOT, texture_2_id, and texture_dim_2.
Referenced by generate_textures().
generate_textures()
void Noise::generate_textures () [private]
Definition at line 34 of file Noise.cpp.
                              {
  generate_num_cells_textures();
  generate_res128_noise_texture();
  generate_res32_noise_texture();
}
References generate_num_cells_textures(), generate_res128_noise_texture(), and generate_res32_noise_texture().
Referenced by Noise(), and update().
print_comp_shader_capabilities()
void Noise::print_comp_shader_capabilities () [private]
Definition at line 102 of file Noise.cpp.
                                           {
  int work_grp_cnt[3];
  glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 0, &work_grp_cnt[0]);
  glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 1, &work_grp_cnt[1]);
  glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 2, &work_grp_cnt[2]);
  printf("max global (total) work group counts x:%i y:%i z:%i\n",
         work_grp_cnt[0], work_grp_cnt[1], work_grp_cnt[2]);
  int work_grp_size[3];
  glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_SIZE, 0, &work_grp_size[0]);
  glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_SIZE, 1, &work_grp_size[1]);
  glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_SIZE, 2, &work_grp_size[2]);
  printf("max local (in one shader) work group sizes x:%i y:%i z:%i\n",
         work_grp_size[0], work_grp_size[1], work_grp_size[2]);
}
read_res128_noise()
void Noise::read_res128_noise ()
Definition at line 265 of file Noise.cpp.
                              {
  GLuint texture_index = GL_TEXTURE0 + NOISE_128D_TEXTURES_SLOT;
  glActiveTexture((GLenum)texture_index);
  glBindTexture(GL_TEXTURE_3D, texture_1_id);
}
References NOISE_128D_TEXTURES_SLOT, and texture_1_id.
read_res32_noise()
void Noise::read_res32_noise ()
Definition at line 271 of file Noise.cpp.
                             {
  GLuint texture_index = GL_TEXTURE0 + NOISE_32D_TEXTURES_SLOT;
  glActiveTexture((GLenum)texture_index);
  glBindTexture(GL_TEXTURE_3D, texture_2_id);
}
References NOISE_32D_TEXTURES_SLOT, and texture_2_id.
set_num_cells()
void Noise::set_num_cells (GLuint num_cells_per_axis, GLuint index)
Definition at line 138 of file Noise.cpp.
                                                                 {
  this->num_cells_per_axis[index] = num_cells_per_axis;
}
References num_cells_per_axis.
update()
void Noise::update ()
Definition at line 122 of file Noise.cpp.
                   {
  delete_textures();
  texture_1_shader_program->reload();
  texture_2_shader_program->reload();
  for (int i = 0; i < NUM_CELL_POSITIONS; i++) {
    generate_cells(num_cells_per_axis[i], i);
  }
  generate_textures();
  create_res128_noise();
  create_res32_noise();
}
References create_res128_noise(), create_res32_noise(), delete_textures(), generate_cells(), generate_textures(), NUM_CELL_POSITIONS, num_cells_per_axis, texture_1_shader_program, and texture_2_shader_program.
Field Documentation
cell_data
std::array<std::vector<GLfloat>, NUM_CELL_POSITIONS> Noise::cell_data [private]
Definition at line 58 of file Noise.h.
Referenced by generate_cells(), and generate_num_cells_textures().
cell_ids
GLuint Noise::cell_ids[NUM_CELL_POSITIONS] [private]
Definition at line 56 of file Noise.h.
Referenced by create_res128_noise(), create_res32_noise(), delete_textures(), and generate_num_cells_textures().
num_cells_per_axis
GLuint Noise::num_cells_per_axis[NUM_CELL_POSITIONS] [private]
Definition at line 57 of file Noise.h.
Referenced by create_res128_noise(), create_res32_noise(), generate_cells(), generate_num_cells_textures(), Noise(), set_num_cells(), and update().
texture_1_id
GLuint Noise::texture_1_id [private]
Definition at line 47 of file Noise.h.
Referenced by delete_textures(), generate_res128_noise_texture(), and read_res128_noise().
texture_1_shader_program
std::shared_ptr<ComputeShaderProgram> Noise::texture_1_shader_program [private]
Definition at line 49 of file Noise.h.
Referenced by create_res128_noise(), create_shader_programs(), and update().
texture_2_id
GLuint Noise::texture_2_id [private]
Definition at line 52 of file Noise.h.
Referenced by delete_textures(), generate_res32_noise_texture(), and read_res32_noise().
texture_2_shader_program
std::shared_ptr<ComputeShaderProgram> Noise::texture_2_shader_program [private]
Definition at line 54 of file Noise.h.
Referenced by create_res32_noise(), create_shader_programs(), and update().
texture_dim_1
GLuint Noise::texture_dim_1 [private]
Definition at line 48 of file Noise.h.
Referenced by create_res128_noise(), and generate_res128_noise_texture().
texture_dim_2
GLuint Noise::texture_dim_2 [private]
Definition at line 53 of file Noise.h.
Referenced by create_res32_noise(), and generate_res32_noise_texture().
The documentation for this class was generated from the following files:
C:/Users/jonas/Desktop/GraphicEngine/Src/scene/atmospheric_effects/clouds/Noise.h
C:/Users/jonas/Desktop/GraphicEngine/Src/scene/atmospheric_effects/clouds/Noise.cpp