GeometryPass Class Reference
#include <GeometryPass.h>
Public Member Functions
GeometryPass ()
void execute (glm::mat4 projection_matrix, std::shared_ptr< Camera > main_camera, GLuint window_width, GLuint window_height, GLuint gbuffer_id, GLfloat delta_time, std::shared_ptr< Scene >)
void create_shader_program ()
void set_game_object_uniforms (glm::mat4 model, glm::mat4 normal_model)
~GeometryPass ()
Private Attributes
std::shared_ptr< GeometryPassShaderProgram > shader_program
SkyBox skybox
Detailed Description
Definition at line 13 of file GeometryPass.h.
Constructor & Destructor Documentation
GeometryPass()
GeometryPass::GeometryPass ()
Definition at line 3 of file GeometryPass.cpp.
: skybox() { create_shader_program(); }
References create_shader_program().
 GeometryPass()
GeometryPass::~GeometryPass ()
Definition at line 137 of file GeometryPass.cpp.
{}
Member Function Documentation
create_shader_program()
void GeometryPass::create_shader_program () [virtual]
Implements RenderPassSceneDependend.
Definition at line 123 of file GeometryPass.cpp.
                                         {
  this->shader_program =
      std::make_shared<GeometryPassShaderProgram>(GeometryPassShaderProgram{});
  this->shader_program->create_from_files(
      "rasterizer/g_buffer_geometry_pass.vert",
      "rasterizer/g_buffer_geometry_pass.frag");
}
References shader_program.
Referenced by GeometryPass().
execute()
void GeometryPass::execute (glm::mat4 projection_matrix, std::shared_ptr< Camera > main_camera, GLuint window_width, GLuint window_height, GLuint gbuffer_id, GLfloat delta_time, std::shared_ptr< Scene > scene)
Definition at line 5 of file GeometryPass.cpp.
                                                       {
  glBindFramebuffer(GL_FRAMEBUFFER, gbuffer_id);
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  glViewport(0, 0, window_width, window_height);
  glEnable(GL_CULL_FACE);
  glCullFace(GL_BACK);
  glFrontFace(GL_CCW);
  shader_program->use_shader_program();
  glm::mat4 view_matrix = main_camera->get_viewmatrix();
  std::vector<ObjMaterial> materials = scene->get_materials();
  shader_program->setUniformMatrix4fv(projection_matrix, "projection");
  shader_program->setUniformMatrix4fv(view_matrix, "view");
  std::stringstream ss;
  for (uint32_t i = 0; i < static_cast<uint32_t>(scene->get_texture_count(0));
       i++) {
    ss << "model_textures[" << i << "]";
    shader_program->setUniformInt(MODEL_TEXTURES_SLOT + i, ss.str());
    ss.clear();
    ss.str(std::string());
  }
  for (uint32_t i = 0; i < static_cast<uint32_t>(materials.size()); i++) {
    ss << "materials[" << i << "].ambient";
    shader_program->setUniformVec3(materials[i].get_ambient(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].diffuse";
    shader_program->setUniformVec3(materials[i].get_diffuse(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].specular";
    shader_program->setUniformVec3(materials[i].get_specular(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].transmittance";
    shader_program->setUniformVec3(materials[i].get_transmittance(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].emission";
    shader_program->setUniformVec3(materials[i].get_emission(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].shininess";
    shader_program->setUniformFloat(materials[i].get_shininess(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].ior";
    shader_program->setUniformFloat(materials[i].get_ior(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].dissolve";
    shader_program->setUniformFloat(materials[i].get_dissolve(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].illum";
    shader_program->setUniformInt(materials[i].get_illum(), ss.str());
    ss.clear();
    ss.str(std::string());
    ss << "materials[" << i << "].textureID";
    shader_program->setUniformInt(materials[i].get_textureID(), ss.str());
    ss.clear();
    ss.str(std::string());
  }
  shader_program->validate_program();
  scene->bind_textures_and_buffer();
  // glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
  // aabb->render();
  // glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
  //
  std::vector<std::shared_ptr<GameObject>> game_objects =
      scene->get_game_objects();
  for (std::shared_ptr<GameObject> object : game_objects) {
    /* if (object_is_visible(object)) {*/
    set_game_object_uniforms(object->get_world_trafo(),
                             object->get_normal_world_trafo());
    object->render();
    //}
  }
  skybox.draw_sky_box(projection_matrix, view_matrix, window_width,
                      window_height, delta_time);
  /*glCullFace(GL_FRONT);
    glFrontFace(GL_CCW);*/
  // render the AABB for the clouds
  glDisable(GL_CULL_FACE);
  std::shared_ptr<Clouds> clouds = scene->get_clouds();
  clouds->render(projection_matrix, view_matrix, window_width, window_height);
  glBindFramebuffer(GL_FRAMEBUFFER, 0);
}
References SkyBox::draw_sky_box(), set_game_object_uniforms(), shader_program, and skybox.
set_game_object_uniforms()
void GeometryPass::set_game_object_uniforms (glm::mat4 model, glm::mat4 normal_model) [virtual]
Implements RenderPassSceneDependend.
Definition at line 131 of file GeometryPass.cpp.
                                                                  {
  shader_program->setUniformMatrix4fv(model, "model");
  shader_program->setUniformMatrix4fv(normal_model, "normal_model");
}
References shader_program.
Referenced by execute().
Field Documentation
shader_program
std::shared_ptr<GeometryPassShaderProgram> GeometryPass::shader_program [private]
Definition at line 28 of file GeometryPass.h.
Referenced by create_shader_program(), execute(), and set_game_object_uniforms().
skybox
SkyBox GeometryPass::skybox [private]
Definition at line 30 of file GeometryPass.h.
Referenced by execute().
The documentation for this class was generated from the following files:
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/renderer/deferred/GeometryPass.h
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/renderer/deferred/GeometryPass.cpp