Window Class Reference
#include <Window.h>
Public Member Functions
Window ()
Window (GLint window_width, GLint window_height)
bool get_should_close ()
void swap_buffers ()
int initialize ()
void update_viewport ()
GLuint get_buffer_width () const
GLuint get_buffer_height () const
GLfloat get_x_change ()
GLfloat get_y_change ()
GLFWwindow * get_window ()
bool * get_keys ()
~Window ()
Private Member Functions
void init_callbacks ()
Static Private Member Functions
static void framebuffer_size_callback (GLFWwindow *window, int width, int height)
static void key_callback (GLFWwindow *window, int key, int code, int action, int mode)
static void mouse_callback (GLFWwindow *window, double x_pos, double y_pos)
static void mouse_button_callback (GLFWwindow *window, int button, int action, int mods)
Private Attributes
GLFWwindow * main_window
GLint window_width
GLint window_height
bool keys [1024]
GLfloat last_x
GLfloat last_y
GLfloat x_change
GLfloat y_change
bool mouse_first_moved
GLint window_buffer_width
GLint window_buffer_height
Detailed Description
Definition at line 7 of file Window.h.
Constructor & Destructor Documentation
Window() [1/2]
Window::Window ()
Definition at line 9 of file Window.cpp.
    : window_width(800), window_height(600), x_change(0.0f), y_change(0.0f) {
  // all keys non-pressed in the beginning
  for (size_t i = 0; i < 1024; i++) {
    keys[i] = 0;
  }
  initialize();
}
References initialize(), and keys.
Window() [2/2]
Window::Window (GLint window_width, GLint window_height)
Definition at line 20 of file Window.cpp.
    :
      window_width(window_width),
      window_height(window_height),
      x_change(0.0f),
      y_change(0.0f) {
  // all keys non-pressed in the beginning
  for (size_t i = 0; i < 1024; i++) {
    keys[i] = 0;
  }
  initialize();
}
References initialize(), and keys.
 Window()
Window::~Window ()
Definition at line 122 of file Window.cpp.
                {
  glfwDestroyWindow(main_window);
  glfwTerminate();
}
References main_window.
Member Function Documentation
framebuffer_size_callback()
void Window::framebuffer_size_callback (GLFWwindow * window, int width, int height) [static], [private]
Definition at line 135 of file Window.cpp.
                                                   {}
Referenced by init_callbacks().
get_buffer_height()
GLuint Window::get_buffer_height () const [inline]
Definition at line 21 of file Window.h.
{ return window_buffer_height; }
References window_buffer_height.
get_buffer_width()
GLuint Window::get_buffer_width () const [inline]
Definition at line 20 of file Window.h.
{ return window_buffer_width; }
References window_buffer_width.
get_keys()
bool * Window::get_keys () [inline]
Definition at line 28 of file Window.h.
{ return keys; }
References keys.
get_should_close()
bool Window::get_should_close () [inline]
Definition at line 12 of file Window.h.
{ return glfwWindowShouldClose(main_window); }
References main_window.
get_window()
GLFWwindow * Window::get_window () [inline]
Definition at line 26 of file Window.h.
{ return main_window; }
References main_window.
get_x_change()
GLfloat Window::get_x_change ()
Definition at line 110 of file Window.cpp.
                             {
  GLfloat the_change = x_change;
  x_change = 0.0f;
  return the_change;
}
References x_change.
get_y_change()
GLfloat Window::get_y_change ()
Definition at line 116 of file Window.cpp.
                             {
  GLfloat the_change = y_change;
  y_change = 0.0f;
  return the_change;
}
References y_change.
init_callbacks()
void Window::init_callbacks () [private]
Definition at line 127 of file Window.cpp.
                            {
  // TODO: remember this section for our later game logic
  // for the space ship to fly around
  glfwSetKeyCallback(main_window, key_callback);
  glfwSetMouseButtonCallback(main_window, mouse_button_callback);
  glfwSetFramebufferSizeCallback(main_window, framebuffer_size_callback);
}
References framebuffer_size_callback(), key_callback(), main_window, and mouse_button_callback().
Referenced by initialize().
initialize()
int Window::initialize ()
Definition at line 35 of file Window.cpp.
                       {
  if (!glfwInit()) {
    printf("GLFW Init failed!");
    glfwTerminate();
    return 1;
  }
  // setup glfw window properties
  // lets work with nothing older than version 3
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 6);
  // core profile = no backward compatibility
  glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
  // allow forward compatibility
  glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  // allow it to resize
  glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
#ifdef NDEBUG
  glfwWindowHint(GLFW_OPENGL_DEBUG_CONTEXT, false);
#else
  glfwWindowHint(GLFW_OPENGL_DEBUG_CONTEXT, true);
#endif
  // retrieve new window
  main_window =
      glfwCreateWindow(window_width, window_height,
                       "\\__/ Epic graphics from hell \\__/", NULL, NULL);
  if (!main_window) {
    printf("GLFW Window creation failed!");
    glfwTerminate();
    return 1;
  }
  // get buffer size information
  glfwGetFramebufferSize(main_window, &window_buffer_width,
                         &window_buffer_height);
  // set context for GLEW to use
  glfwMakeContextCurrent(main_window);
  if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
    std::cout << "Failed to initialize OpenGL context" << std::endl;
    return -1;
  }
  // disabling frame limits
  glfwSwapInterval(0);
  // Handle key + mouse Input
  init_callbacks();
  glfwSetInputMode(main_window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
  glEnable(GL_DEPTH_TEST);
  // setup viewport size
  glViewport(0, 0, window_buffer_width, window_buffer_height);
  glfwSetWindowUserPointer(main_window, this);
  return 0;
}
References init_callbacks(), main_window, window_buffer_height, window_buffer_width, window_height, and window_width.
Referenced by Window().
key_callback()
void Window::key_callback (GLFWwindow * window, int key, int code, int action, int mode) [static], [private]
Definition at line 138 of file Window.cpp.
                                    {
  Window* the_window = static_cast<Window*>(glfwGetWindowUserPointer(window));
  if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
    glfwSetWindowShouldClose(window, GL_TRUE);
  }
  if (key >= 0 && key < 1024) {
    if (action == GLFW_PRESS) {
      the_window->keys[key] = true;
    } else if (action == GLFW_RELEASE) {
      the_window->keys[key] = false;
    }
  }
}
References keys.
Referenced by init_callbacks().
mouse_button_callback()
void Window::mouse_button_callback (GLFWwindow * window, int button, int action, int mods) [static], [private]
Definition at line 175 of file Window.cpp.
                                             {
  if (ImGui::GetCurrentContext() != nullptr &&
      ImGui::GetIO().WantCaptureMouse) {
    ImGuiIO& io = ImGui::GetIO();
    io.AddMouseButtonEvent(button, action);
    return;
  }
  Window* the_window = static_cast<Window*>(glfwGetWindowUserPointer(window));
  if ((action == GLFW_PRESS) && (button == GLFW_MOUSE_BUTTON_RIGHT)) {
    glfwSetCursorPosCallback(window, mouse_callback);
  } else {
    the_window->mouse_first_moved = true;
    glfwSetCursorPosCallback(window, NULL);
  }
}
References mouse_callback(), and mouse_first_moved.
Referenced by init_callbacks().
mouse_callback()
void Window::mouse_callback (GLFWwindow * window, double x_pos, double y_pos) [static], [private]
Definition at line 156 of file Window.cpp.
                                                                          {
  Window* the_window = static_cast<Window*>(glfwGetWindowUserPointer(window));
  // need to handle first occurance of a mouse moving event
  if (the_window->mouse_first_moved) {
    the_window->last_x = (float)x_pos;
    the_window->last_y = (float)y_pos;
    the_window->mouse_first_moved = false;
  }
  the_window->x_change = (float)(x_pos - the_window->last_x);
  // take care of correct substraction :)
  the_window->y_change = (float)(the_window->last_y - y_pos);
  // update params
  the_window->last_x = (float)x_pos;
  the_window->last_y = (float)y_pos;
}
References last_x, last_y, mouse_first_moved, x_change, and y_change.
Referenced by mouse_button_callback().
swap_buffers()
void Window::swap_buffers () [inline]
Definition at line 13 of file Window.h.
{ glfwSwapBuffers(main_window); }
References main_window.
update_viewport()
void Window::update_viewport ()
Definition at line 103 of file Window.cpp.
                             {
  glfwGetFramebufferSize(main_window, &window_buffer_width,
                         &window_buffer_height);
  // setup viewport size
  glViewport(0, 0, window_buffer_width, window_buffer_height);
}
References main_window, window_buffer_height, and window_buffer_width.
Field Documentation
keys
bool Window::keys[1024] [private]
Definition at line 37 of file Window.h.
Referenced by get_keys(), key_callback(), and Window().
last_x
GLfloat Window::last_x [private]
Definition at line 38 of file Window.h.
Referenced by mouse_callback().
last_y
GLfloat Window::last_y [private]
Definition at line 39 of file Window.h.
Referenced by mouse_callback().
main_window
GLFWwindow* Window::main_window [private]
Definition at line 33 of file Window.h.
Referenced by get_should_close(), get_window(), init_callbacks(), initialize(), swap_buffers(), update_viewport(), and ~Window().
mouse_first_moved
bool Window::mouse_first_moved [private]
Definition at line 42 of file Window.h.
Referenced by mouse_button_callback(), and mouse_callback().
window_buffer_height
GLint Window::window_buffer_height [private]
Definition at line 45 of file Window.h.
Referenced by get_buffer_height(), initialize(), and update_viewport().
window_buffer_width
GLint Window::window_buffer_width [private]
Definition at line 45 of file Window.h.
Referenced by get_buffer_width(), initialize(), and update_viewport().
window_height
GLint Window::window_height [private]
Definition at line 35 of file Window.h.
Referenced by initialize().
window_width
GLint Window::window_width [private]
Definition at line 35 of file Window.h.
Referenced by initialize().
x_change
GLfloat Window::x_change [private]
Definition at line 40 of file Window.h.
Referenced by get_x_change(), and mouse_callback().
y_change
GLfloat Window::y_change [private]
Definition at line 41 of file Window.h.
Referenced by get_y_change(), and mouse_callback().
The documentation for this class was generated from the following files:
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/window/Window.h
C:/Users/jonas_l6e3q/Desktop/GraphicEngine/Src/window/Window.cpp