#ifndef GLOBALS_HOST_DEVICE
#define GLOBALS_HOST_DEVICE
//define all constants here
const int NUM_CASCADES = 3;
const int MAX_POINT_LIGHTS = 1;

const int MAX_MATERIALS = 35;
const int SKYBOX_MATERIAL_ID = MAX_MATERIALS;
const int CLOUDS_MATERIAL_ID = MAX_MATERIALS + 1;

const int MAX_TEXTURE_COUNT = 30;

const float PI = 3.14159265359f;

// bindings 
#define STORAGE_BUFFER_MATERIAL_ID_BINDING 0
#define UNIFORM_LIGHT_MATRICES_BINDING 1

#endif // !GLOBALS_HOST_DEVICE


