# setting all shader filters
# ---- SHADER FILTER  --- BEGIN
set(SHADER_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Resources/Shaders/)

# ---- SHADER SKYBOX FILTER  --- BEGIN
set(SHADER_SKYBOX_SRC_DIR ${SHADER_SRC_DIR}skybox/)
set(SKYBOX_SHADER_FILTER ${SKYBOX_SHADER_FILTER}
    ${SHADER_SKYBOX_SRC_DIR}SkyBox.frag
    ${SHADER_SKYBOX_SRC_DIR}SkyBox.vert
)
# ---- SHADER SKYBOX FILTER  --- END

# ---- SHADER RASTERIZER FILTER  --- BEGIN
set(SHADER_RASTERIZER_SRC_DIR ${SHADER_SRC_DIR}rasterizer/)
set(RASTERIZER_SHADER_FILTER ${RASTERIZER_SHADER_FILTER}
    ${SHADER_RASTERIZER_SRC_DIR}g_buffer_geometry_pass.vert
    ${SHADER_RASTERIZER_SRC_DIR}g_buffer_geometry_pass.frag
    ${SHADER_RASTERIZER_SRC_DIR}g_buffer_lighting_pass.vert
    ${SHADER_RASTERIZER_SRC_DIR}g_buffer_lighting_pass.frag
)
# ---- SHADER RASTERIZER FILTER  --- END

# ---- SHADER FILTER  --- END
